version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
            echo "source $HOME/.nix-profile/etc/profile.d/nix.sh" >> $BASH_ENV
      - run:
          name: Build images
          command: nix-shell --run nix-docker-build
      - run:
          name: Push images to Dockerh Hub if on master branch
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
                echo "On master branch, pushing images to Docker Hub..."
                docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
                nix-shell --run nix-docker-push
            else
                echo "Not on master branch, skipping pushing to Docker Hub."
            fi
